language: python

python:
  - "3.6"

cache: pip

# temporarily pin pydocstyle for reason here:
# https://gitlab.com/pycqa/flake8-docstrings/issues/36
install:
  - pip install -r test_requirements.txt
  - pip install -e .

script: 
  - flake8
  - pytest

branches:
  only:
    - master

notifications:
  slack: jbloomlab:M5Ap209HwoU6g0ECE137npd5
